services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: nikitha84/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb  #here dependency is mongodb.so 1st mongodb will created 2nd catalogue

  mongodb: #-- name mongodb
    build: ./mongodb
    image: nikitha84/mongodb:v1  #image push in dockerhub
    container_name: mongodb
    volumes:
    - mongodb:/data/db #container path stord in host path

  redis: #-- name mongodb
    image: redis:7 #image
    container_name: redis
    volumes:
    - redis:/data

  # mysql: #-- name mongodb
  #   build: ./mysql
  #   image: nikitha84/mysql:v1  #image
  #   container_name: mysql
  #   volumes:
  #   - mysql:/var/lib/mysql

  # rabbitmq: #-- name mongodb
  #   image: rabbitmq:v1  #image
  #   container_name: rabbitmq
  #   volumes:
  #   - rabbitmq:/var/lib/rabbitmq
  #   environment:
  #    RABBITMQ_DEFAULT_USER: roboshop
  #    RABBITMQ_DEFAULT_PASS: roboshop123

  user:
    build: ./user
    image: nikitha84/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis 
  cart:
    build: ./cart
    image: nikitha84/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  # shipping:
   #   build: ./shipping
  #   image: shipping:v1
  #   container_name: shipping
  #   depends_on:
  #   - mysql
  #   - cart
  # payment:
  #   build: ./shipping
  #   image: payment:v1
  #   container_name: payment
  #   depends_on:
  #   - rabbitmq
  #   - cart
  #   - user
  frontend:
    build: ./frontend
    image: nikitha84/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    

networks:
  default: #set as roboshop n/w is default n/w
    external: false
    driver: bridge
    name: roboshop #true: if u create manually n/w using docker create network roboshop cmd.now i m saying to docker compose create n/w
volumes:
  mongodb: #docker host path
  redis:
  # rabbitmq:
  #mysql:



